### ISSUE TITLE
Font of the formulas is bad

### ISSUE THREAD

**Issue by theocheslerean** [Rostlab/JS16_ProjectF#391]
![screenshot_2016-04-11-09-54-05](https://cloud.githubusercontent.com/assets/12728596/14420329/c3eaae9a-ffcb-11e5-9a83-c49c6940db84.png)

**Comment by sacdallago** [comment]
That's because the formulas are PNG images.
Is that markdown interpreted text? Does someone know what Markdown parser is used?

https://github.com/cben/mathdown/wiki/math-in-markdown

**Comment by yashha** [comment]
we are using the react 'markdown-loader' which is using marked

**Comment by sacdallago** [comment]
Me and @goldbergtatyana  have been giving a look, there seems to be no support for formulas out of the box for marked. @goldbergtatyana will produce some new images

**Comment by goldbergtatyana** [comment]
I regenerated formulas with the simple power point this time and updated the plod-description.md file to remove descriptions of algo2.

**Comment by yashha** [comment]
See like still no images :disappointed:

**Comment by sacdallago** [comment]
Hey I am with @goldbergtatyana and we were having a look at the output of the interpreted markdown and it would be nice if you could add the following CSS befaviours:

``` css
table {
  width: 100%;
  border-top: 1px solid white;
  border-bottom: 1px solid white;
  font-size: 17px;
}

thead {
  border-bottom: 1px solid white;
}
```

Eventually also

``` css
body {
  font-size: 17px;
}
```
